media: images
content:
  - name: projets
    label: Projets
    type: collection
    path: projets/
    fields:
      - name: projet
        label: Projet
        type: string
      - name: description
        label: Description
        type: string
      - name: année
        label: Année
        type: string
      - name: lieu
        label: Lieu
        type: string
      - name: photos
        label: Photos
        type: block
        list: true # Often used with type: block to allow multiple sections
        blocks:
          - name: hero
                label: Add Hero Section
                component: hero
          - name: text
                label: Add Text Block
                fields:
                  - name: content
                    label: Text Content
                    type: rich-text
